import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import {
  MatCardModule,
  MatToolbarModule,
  MatDatepickerModule,
  MatNativeDateModule,
  MatButtonModule,
  MatIconModule,
  MatSidenavModule,
  MatListModule,
  MatTableModule,
  MatSortModule,
  MatTooltipModule ,
  MatChipsModule,
  MatCheckboxModule,
  MatAutocompleteModule,
  MatProgressBarModule,
  MatInputModule,
  MatExpansionModule,
  MatGridListModule,
  MatButtonToggleModule,
  MatSnackBarModule,
  MatMenuModule,
  MatProgressSpinnerModule,
  MatSelectModule,
  MatFormFieldModule,
} from '@angular/material';
import { DxDataGridModule, DxButtonModule } from 'devextreme-angular';

@NgModule({
  imports: [
    CommonModule,
    MatCardModule,
    MatToolbarModule,
    MatDatepickerModule,
    MatNativeDateModule,
    MatButtonModule,
    MatIconModule,
    MatSidenavModule,
    MatListModule,
    MatTableModule,
    MatSortModule,
    MatTooltipModule ,
    MatChipsModule,
    MatCheckboxModule,
    MatAutocompleteModule,
    MatProgressBarModule,
    MatInputModule,
    MatExpansionModule,
    MatGridListModule,
    MatButtonToggleModule,
    MatSnackBarModule,
    MatMenuModule,
    MatProgressSpinnerModule,
    MatSelectModule,
    MatFormFieldModule,
    DxDataGridModule, DxButtonModule
  ],
  exports: [
    MatCardModule,
    MatToolbarModule,
    MatDatepickerModule,
    MatNativeDateModule,
    MatButtonModule,
    MatIconModule,
    MatSidenavModule,
    MatListModule,
    MatTableModule,
    MatSortModule,
    MatTooltipModule ,
    MatChipsModule,
    MatCheckboxModule,
    MatAutocompleteModule,
    MatProgressBarModule,
    MatInputModule,
    MatExpansionModule,
    MatGridListModule,
    MatButtonToggleModule,
    MatSnackBarModule,
    MatMenuModule,
    MatProgressSpinnerModule,
    MatSelectModule,
    MatFormFieldModule,
    DxDataGridModule, DxButtonModule
  ],
  declarations: []
})
export class AngularMaterialModule { }
